TARGET := iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = Facebook

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = FacebookNoSeen

FacebookNoSeen_FILES = Tweak.x
FacebookNoSeen_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
